# Common properties
spring.application.name=Hackeralgo Mobile App Backend Rest API Module
server.port=8080
spring.security.user.name=hackeralgoadmin
spring.security.user.password=adminpassword
spring.security.basic.enabled=false

spring.jackson.time-zone=Asia/Kolkata
file.upload-dir=./uploads

# Development profile
spring.config.activate.on-profile=dev
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=pass
spring.sql.init.platform=h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Production profile
spring.config.activate.on-profile=prod
spring.datasource.url=jdbc:mysql://localhost:3306/prod_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=prod_user
spring.datasource.password=prod_password
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false